services:
  rtstt:
    build:
      context: .
      target: gpu # or cpu
    image: rtstt
    container_name: rtstt
    volumes:
      # - ./RealtimeSTT:/app/RealtimeSTT
      # - ./example_browserclient:/app/example_browserclient
      - cache:/root/.cache
      - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "8001:8001"
      - "8002:8002"
    # if 'gpu' target
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8081:80"
      - "8082:443"
    volumes:
      - ./example_browserclient:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/ssl

volumes:
  cache:
