@echo off
setlocal

rem Run from the repository root, or double-click from this folder.
set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%\.." >nul

if not defined PYTHON_EXE if defined VIRTUAL_ENV set "PYTHON_EXE=%VIRTUAL_ENV%\Scripts\python.exe"
if not defined PYTHON_EXE set "PYTHON_EXE=python"

if not defined REALTIMESTT_RUN_FASTAPI_MULTI_USER_PERF set "REALTIMESTT_RUN_FASTAPI_MULTI_USER_PERF=1"
if not defined REALTIMESTT_FASTAPI_ASR_CLIENTS set "REALTIMESTT_FASTAPI_ASR_CLIENTS=4"
if not defined REALTIMESTT_FASTAPI_ASR_METRICS_JSON set "REALTIMESTT_FASTAPI_ASR_METRICS_JSON=test-results\fastapi-%REALTIMESTT_FASTAPI_ASR_CLIENTS%-user-perf.json"

if not defined REALTIMESTT_FASTAPI_ASR_ENGINE set "REALTIMESTT_FASTAPI_ASR_ENGINE=sherpa_onnx_moonshine"
if not defined REALTIMESTT_FASTAPI_ASR_MODEL set "REALTIMESTT_FASTAPI_ASR_MODEL=sherpa-onnx-moonshine-base-en-int8"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_ENGINE set "REALTIMESTT_FASTAPI_ASR_REALTIME_ENGINE=sherpa_onnx_moonshine"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_MODEL set "REALTIMESTT_FASTAPI_ASR_REALTIME_MODEL=sherpa-onnx-moonshine-tiny-en-int8"
if not defined REALTIMESTT_FASTAPI_ASR_DEVICE set "REALTIMESTT_FASTAPI_ASR_DEVICE=cpu"
if not defined REALTIMESTT_FASTAPI_ASR_DOWNLOAD_ROOT set "REALTIMESTT_FASTAPI_ASR_DOWNLOAD_ROOT=test-model-cache\sherpa-onnx"

if not defined REALTIMESTT_FASTAPI_ASR_ENGINE_OPTIONS set "REALTIMESTT_FASTAPI_ASR_ENGINE_OPTIONS=num_threads=4,provider=cpu"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_ENGINE_OPTIONS set "REALTIMESTT_FASTAPI_ASR_REALTIME_ENGINE_OPTIONS=num_threads=2,provider=cpu"

if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_PROCESSING_PAUSE set "REALTIMESTT_FASTAPI_ASR_REALTIME_PROCESSING_PAUSE=0.8"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_USE_SYLLABLE_BOUNDARIES set "REALTIMESTT_FASTAPI_ASR_REALTIME_USE_SYLLABLE_BOUNDARIES=1"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_BOUNDARY_DETECTOR_SENSITIVITY set "REALTIMESTT_FASTAPI_ASR_REALTIME_BOUNDARY_DETECTOR_SENSITIVITY=0.6"
if not defined REALTIMESTT_FASTAPI_ASR_REALTIME_BOUNDARY_FOLLOWUP_DELAYS set "REALTIMESTT_FASTAPI_ASR_REALTIME_BOUNDARY_FOLLOWUP_DELAYS=0.1,0.2,0.4"

echo Running FastAPI multi-user performance test with %REALTIMESTT_FASTAPI_ASR_CLIENTS% clients...
echo Metrics JSON: %REALTIMESTT_FASTAPI_ASR_METRICS_JSON%
echo.

"%PYTHON_EXE%" -m unittest -v tests.unit.test_fastapi_server_multi_user_asr_integration.FastAPIMultiUserRealEngineASRTests
set "EXIT_CODE=%ERRORLEVEL%"

popd >nul
exit /b %EXIT_CODE%
